In [4]:
import pandas as pd
import os

In [5]:
folder = '/home/laura/IMPORTANTE/Papers/Klebsiella/Brote_Mich/Brote_180523/Compare/2023-05-18_Compare/'
revised_final = 'Compare.revised.final.csv'
database_file = os.path.join(folder, revised_final)
rdf_final = 'Compare.revised.rdf'
rdf_file = os.path.join(folder, rdf_final)

In [12]:
def import_to_pandas(file_table, header=False, sep='\t'):
    if header == False:
        # exclude first line, exclusive for vcf outputted by PipelineTB
        dataframe = pd.read_csv(file_table, sep=sep, skiprows=[0], header=None)
    else:
        # Use first line as header
        dataframe = pd.read_csv(file_table, sep=sep, header=0)

    return dataframe

In [3]:
def matrix_to_rdf(snp_matrix, output_name):
    # snp_matrix = import_to_pandas(tsv_matrix, header=True)
    # tsv_matrix = os.path.abspath(tsv_matrix)
    # output_name = ".".join(tsv_matrix.split(".")[:-1]) + ".rdf"
    # output_name = output_name + ".rdf"

    # max_samples = max(snp_matrix.N.tolist())
    # snp_matrix = snp_matrix[snp_matrix.N < max_samples]

    with open(output_name, 'w+') as fout:
        snp_number = snp_matrix.shape[0]
        first_line = "  ;1.0\n"
        # logger.info(first_line)
        fout.write(first_line)
        snp_list = snp_matrix.Position.tolist()
        snp_list = [x.split('|')[2] for x in snp_list]
        snp_list = " ;".join([str(x) for x in snp_list]) + " ;\n"
        # logger.info(snp_list)
        fout.write(snp_list)
        third_line = ("10;" * snp_number) + "\n"
        # logger.info(third_line)
        fout.write(third_line)
        transposed_snp_matrix = snp_matrix.T
        for index, row in transposed_snp_matrix.iloc[3:, :].iterrows():
            sample_header = ">" + index+";1;;;;;;;\n"
            # logger.info(sample_header)
            fout.write(sample_header)
            snp_row = "".join([str(x) for x in row.tolist()]) + "\n"
            # logger.info(snp_row)
            fout.write(snp_row)
        ref_header = ">REF;1;;;;;;;\n"
        # logger.info(ref_header)
        fout.write(ref_header)
        ref_snp = "0" * snp_number
        # logger.info(ref_snp)
        fout.write(ref_snp)

In [14]:
import_to_pandas(database_file, header=True, sep='\t')

,Position,N,198-21,21139880,21456269,21465953,21526733,22075652,22111145-BIS,22126531,...,22206299,2307-20,2714-21,2890-21BIS,3076-21,3077-20,3216-20,3228-21,840-21,904-21
0,NZ_AP022547.1|C|577|T,19,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
1,NZ_AP022547.1|C|623|T,19,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
2,NZ_AP022547.1|A|685|G,19,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
3,NZ_AP022547.1|T|724|C,19,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
4,NZ_AP022547.1|C|2258|T,19,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29641,NZ_AP022547.1|G|3387780|A,1,0,0,0,0,0,0,0,0,...,0,0,0,1,0,0,0,0,0,0
29642,NZ_AP022547.1|T|4602536|C,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
29643,NZ_AP022547.1|A|4817677|T,1,0,0,0,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0
29644,NZ_AP022547.1|A|5166630|T,1,0,0,0,0,0,1,0,0,...,0,0,0,0,0,0,0,0,0,0
29645,NZ_AP022547.1|C|5918123|A,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0

In [16]:
presence_ddbb = import_to_pandas(database_file, header=True, sep='\t')

In [17]:
matrix_to_rdf(presence_ddbb, rdf_file)